packages:
  - packages/**/*
  - packages/astro/test/units/_temp-fixtures
  - examples/**/*
  - triage/*
  - smoke/**/*
  - temp/*
  - scripts
  - benchmark
  - benchmark/packages/*
  - benchmark/static-projects/*
  - '!packages/astro/test/units/_temp-fixtures/*'
  - '!**/.vercel/**'

autoInstallPeers: false

linkWorkspacePackages: true

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - '@flue/*'
  - '@astrojs/*'
  - fast-xml-parser@5.3.8
  - svelte@5.53.5
  - fastify@5.8.1 || 5.8.3
  - rollup@4.59.0
  - undici@7.24.0
  - smol-toml@1.6.1
  - picomatch@4.0.4

onlyBuiltDependencies:
  - esbuild
  - workerd
  - '@biomejs/biome'
  - sharp
  - '@parcel/watcher'
  - keytar
  - '@vscode/vsce-sign'

overrides:
  defu@<=6.1.4: '>=6.1.5'
  yaml@>=2.0.0 <2.8.3: '>=2.8.3'

peerDependencyRules:
  allowAny:
    - astro
    - vite

preferWorkspacePackages: true

saveWorkspaceProtocol: false
